apiVersion: apps/v1
kind: Deployment

metadata:
  name: spring-boot-app-deploy

spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1


  selector:
    matchLabels:
      tier: frontend

  template:
    metadata:
      labels:
        tier: frontend

    spec:
      containers:
        - name: spring-boot-container
          image: far2005/spring-demo-app:3.0.0
